version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: modelo-consolidacao-rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - "./data:/var/lib/rabbitmq/"
    networks:
      - rabbitmq

  itunesws:
    image: vellos/itunesws:latest
    container_name: itunesws
    restart: always
    ports:
      - 5555:80
    environment: 
      - ITUNESWS_UTILS_RABBITMQ_HOST=rabbitmq
    networks:
      - rabbitmq

  savedataapi:
    image: vellos/savedataapi:latest
    container_name: savedataapi
    restart: always
    ports:
      - 4444:4444
    environment: 
      - SAVE_DATA_API_UTILS_RABBITMQ_HOST=rabbitmq
      - SAVE_DATA_API_SPRING_DATA_MONGODB_HOST=itunesdb
    networks:
      - rabbitmq
      - mongodb

  itunesdb:
    image: mongo
    container_name: itunesdb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    environment: 
      - MONGO_INITDB_DATABASE=itunesdata
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - mongodb

networks:
  itunesws:
  rabbitmq:
  mongodb:

volumes:
  mongodb:
  mongoconfig: