server:
  port: ${itunesws.properties.server.port}
  error:
    includeStacktrace: ${itunesws.properties.server.error.includeStacktrace}
    whitelabel:
      enabled: ${itunesws.properties.server.error.whitelabel.enabled}

logging:
  level:
    web: ${itunesws.properties.logging.level.web}

spring:
  main:
    allowBeanDefinitionOverriding: ${itunesws.properties.spring.main.allowBeanDefinitionOverriding}
  devtools:
    addProperties: ${itunesws.properties.spring.devtools.addProperties}
  rabbitmq:
    host: ${itunesws.properties.utils.rabbitmq.host}
    port: ${itunesws.properties.utils.rabbitmq.port}
    username: ${itunesws.properties.utils.rabbitmq.username}
    password: ${itunesws.properties.utils.rabbitmq.password}
    queues:
      iTunesSaveDataQueue:
        name: ${itunesws.properties.utils.rabbitmq.queues.iTunesSaveDataQueue.name}

itunesws:
  properties:
    server:
      port: ${ITUNESWS_SERVER_PORT:80}
      error:
        includeStacktrace: ${ITUNESWS_SERVER_ERROR_INCLUDE_STACK_TRACE:never}
        whitelabel:
          enabled: ${ITUNESWS_SERVER_ERROR_WHITELABEL_ENABLED:true}

    logging:
      level:
        web: ${ITUNESWS_LOGGING_LEVEL_WEB:error}

    spring:
      main:
        allowBeanDefinitionOverriding: ${ITUNESWS_SPRING_BEAN_DEFINITION_OVERRIDING:true}
      devtools:
        addProperties: ${ITUNESWS_SPRING_DEVTOOLS_ADD_PROPERTIES:true}

    utils:
      rabbitmq:
        host: ${ITUNESWS_UTILS_RABBITMQ_HOST:localhost}
        port: ${ITUNESWS_UTILS_RABBITMQ_PORT:5672}
        username: ${ITUNESWS_UTILS_RABBITMQ_USERNAME:root}
        password: ${ITUNESWS_UTILS_RABBITMQ_PASSWORD:root}
        queues:
          iTunesSaveDataQueue:
            name: ${ITUNESWS_UTILS_RABBITMQ_QUEUES_ITUNES_DATA_QUEUE_NAME:iTunesSaveDataQueue}
        image:
          name: ${ITUNESWS_UTILS_RABBITMQ_IMAGE_NAME:rabbitmq}
          version: ${ITUNESWS_UTILS_RABBITMQ_IMAGE_VERSION:latest}

    auth:
      basic:
        username: ${ITUNESWS_AUTH_BASIC_USERNAME:root}
        password: ${ITUNESWS_AUTH_BASIC_PASSWORD:root}

    cors:
      allowedOrigins: ${ITUNESWS_CORS_ALLOWED_ORIGINS:*}
      allowedMethods: ${ITUNESWS_CORS_ALLOWED_METHODS:GET, OPTIONS}
      allowedHeaders: ${ITUNESWS_CORS_ALLOWED_HEADERS:*}

    itunesApi:
      protocol: ${ITUNESWS_ITUNES_API_PROTOCOL:http}
      url: ${ITUNESWS_ITUNES_API_URL:itunes.apple.com}

    swagger:
      enabled: ${ITUNESWS_SWAGGER_ENABLED:true}
      paths: ${ITUNESWS_SWAGGER_PATHS:/v2/api-docs, /swagger-resources/configuration/ui, /swagger-resources, /swagger-resources/configuration/security, /swagger-ui/, /swagger-ui.html, /webjars/**}
